import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { CATALOGUE, SURVEY_ITEM, blueprintItemId, structureId } from "../scripts/core/blueprint";

/**
 * A catalogue key becomes two runtime-built ids: `builder:<key>`, handed to
 * `world.structureManager.get`, and `builder:blueprint_<key>`, the item the
 * kids hold. Neither is checked by the compiler, and neither fails loudly:
 * `structureManager.get` returns undefined for a name nothing ships, and an
 * item id that names no item simply never appears in anyone's hand. So a
 * renamed key, or a catalogue entry added before its files are generated,
 * is green in CI and inert in game.
 *
 * `blueprint.test.ts` already holds the ids to their shape and to the
 * generator's `BUILDINGS`. This holds them to the files the pack actually
 * ships, which is the half that can drift on its own - the assets are
 * generated by `npm run assets` and committed (CLAUDE.md rule 5), so a
 * missing one means the generator was not re-run.
 */

const PACK = join(__dirname, "..", "behavior_pack");
const STRUCTURES = join(PACK, "structures", "builder");
const ITEMS = join(PACK, "items");

describe("every catalogue entry ships the files its ids name", () => {
  it("has a .mcstructure for every key", () => {
    const missing = CATALOGUE.filter((e) => !existsSync(join(STRUCTURES, `${e.key}.mcstructure`))).map((e) => e.key);
    expect(missing, `structureManager.get would return undefined for ${missing.map(structureId).join(", ")}`).toEqual([]);
  });

  it("has a blueprint item for every key, declaring the id the script builds", () => {
    for (const entry of CATALOGUE) {
      const file = join(ITEMS, `blueprint_${entry.key}.json`);
      expect(existsSync(file), `no item file for ${blueprintItemId(entry.key)} (expected items/blueprint_${entry.key}.json)`).toBe(true);
      if (!existsSync(file)) continue;
      const id = JSON.parse(readFileSync(file, "utf8"))["minecraft:item"].description.identifier as string;
      expect(id, `blueprint_${entry.key}.json declares ${id}`).toBe(blueprintItemId(entry.key));
    }
  });

  it("ships the survey blueprint the script hands out", () => {
    const file = join(ITEMS, "blueprint_survey.json");
    expect(existsSync(file), `no item file for ${SURVEY_ITEM}`).toBe(true);
    const id = JSON.parse(readFileSync(file, "utf8"))["minecraft:item"].description.identifier as string;
    expect(id).toBe(SURVEY_ITEM);
  });

  it("has no catalogue key twice", () => {
    const keys = CATALOGUE.map((e) => e.key);
    expect(new Set(keys).size, `duplicate key(s) in the catalogue: ${keys.join(", ")}`).toBe(keys.length);
  });

  /**
   * A survey key is `survey_<n>`, minted at runtime, and `catalogueEntry`
   * synthesises its entry - so a fixed key shaped like one would be
   * shadowed by a survey the kids took.
   */
  it("has no fixed key that a survey could be mistaken for", () => {
    const clashes = CATALOGUE.filter((e) => /^survey_\d+$/.test(e.key)).map((e) => e.key);
    expect(clashes, `catalogue key(s) collide with the survey scheme: ${clashes.join(", ")}`).toEqual([]);
  });
});
